name: dds
channels:
  - nvidia/label/cuda-11.3.0
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.10.11=h06a4308_0
  - certifi=2022.9.24=py310h06a4308_0
  - cuda-nvcc=11.3.58=h2467b9f_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.3=h5eee18b_3
  - openssl=1.1.1s=h7f8727e_0
  - python=3.10.8=haa1d7c7_0
  - readline=8.2=h5eee18b_0
  - setuptools=65.5.0=py310h06a4308_0
  - sqlite=3.39.3=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - tzdata=2022f=h04d1e81_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.6=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - absl-py==1.3.0
    - anyio==3.6.2
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.1.0
    - astunparse==1.6.3
    - attrs==22.1.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.1
    - cachetools==5.2.0
    - cffi==1.15.1
    - charset-normalizer==2.1.1
    - chex==0.1.5
    - click==8.1.3
    - cloudpickle==2.2.0
    - contextlib2==21.6.0
    - contourpy==1.0.6
    - cycler==0.11.0
    - debugpy==1.6.3
    - decorator==5.1.1
    - defusedxml==0.7.1
    - dill==0.3.6
    - distrax==0.1.2
    - dm-haiku==0.0.9
    - dm-tree==0.1.7
    - docker-pycreds==0.4.0
    - entrypoints==0.4
    - etils==0.9.0
    - exceptiongroup==1.0.4
    - executing==1.2.0
    - fastjsonschema==2.16.2
    - flatbuffers==22.10.26
    - fonttools==4.38.0
    - gast==0.4.0
    - gitdb==4.0.9
    - gitpython==3.1.29
    - google-auth==2.14.1
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - googleapis-common-protos==1.57.0
    - grpcio==1.50.0
    - h5py==3.7.0
    - idna==3.4
    - importlib-resources==5.10.0
    - inference-gym==0.0.4
    - iniconfig==1.1.1
    - ipykernel==6.17.1
    - ipython==8.6.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.2
    - jax==0.3.25
    - jaxlib==0.3.25
    - jedi==0.18.1
    - jinja2==3.1.2
    - jmp==0.0.2
    - jsonschema==4.17.0
    - jupyter==1.0.0
    - jupyter-client==7.4.7
    - jupyter-console==6.4.4
    - jupyter-core==5.0.0
    - jupyter-server==1.23.2
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.3
    - keras==2.11.0
    - kiwisolver==1.4.4
    - libclang==14.0.6
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.6.2
    - matplotlib-inline==0.1.6
    - mistune==2.0.4
    - ml-collections==0.1.1
    - multipledispatch==0.6.0
    - nbclassic==0.4.8
    - nbclient==0.7.0
    - nbconvert==7.2.5
    - nbformat==5.7.0
    - nest-asyncio==1.5.6
    - notebook==6.5.2
    - notebook-shim==0.2.2
    - numpy==1.23.5
    - numpyro==0.10.1
    - oauthlib==3.2.2
    - opt-einsum==3.3.0
    - optax==0.1.3
    - packaging==21.3
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathtools==0.1.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.3.0
    - pip==22.3.1
    - platformdirs==2.5.4
    - pluggy==1.0.0
    - prometheus-client==0.15.0
    - promise==2.3
    - prompt-toolkit==3.0.32
    - protobuf==3.19.6
    - psutil==5.9.4
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.21
    - pygments==2.13.0
    - pyparsing==3.0.9
    - pyrsistent==0.19.2
    - pytest==7.2.0
    - python-dateutil==2.8.2
    - pyyaml==6.0
    - pyzmq==24.0.1
    - qtconsole==5.4.0
    - qtpy==2.3.0
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scipy==1.9.3
    - send2trash==1.8.0
    - sentry-sdk==1.11.0
    - setproctitle==1.3.2
    - shortuuid==1.0.11
    - six==1.16.0
    - smmap==5.0.0
    - sniffio==1.3.0
    - soupsieve==2.3.2.post1
    - stack-data==0.6.1
    - tabulate==0.9.0
    - tensorboard==2.11.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.11.0
    - tensorflow-datasets==4.7.0
    - tensorflow-estimator==2.11.0
    - tensorflow-io-gcs-filesystem==0.27.0
    - tensorflow-metadata==1.11.0
    - tensorflow-probability==0.18.0
    - termcolor==2.1.1
    - terminado==0.17.0
    - tfp-nightly==0.19.0.dev20221120
    - tinycss2==1.2.1
    - toml==0.10.2
    - tomli==2.0.1
    - toolz==0.12.0
    - tornado==6.2
    - tqdm==4.64.1
    - traitlets==5.5.0
    - typing-extensions==4.4.0
    - urllib3==1.26.12
    - wandb==0.13.5
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.4.2
    - werkzeug==2.2.2
    - widgetsnbextension==4.0.3
    - wrapt==1.14.1
    - zipp==3.10.0
    - git+https://github.com/deepmind/jaxline
    - git+https://github.com/franciscovargas/annealed_flow_transport
prefix: /home/sp2058/.conda/envs/dds
